# OctoCoder model, 15B parameters, max_seq_length 8K
# Based on: https://arxiv.org/abs/2308.07124

train_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./shuffled/starcoder_data_test/val"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 18
    shuffle: False
    shuffle_seed: 1
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

eval_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./shuffled/starcoder_data_test/test"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 18
    shuffle: False
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

model:
    # Embedding
    vocab_size: 49152
    position_embedding_type: "learned"
    embedding_dropout_rate: 0.1
    share_embedding_weights: True # no config default values, HF uses tie_weights as default

    # Decoder Block
    hidden_size: 6144
    filter_size: 24576
    num_heads: 48
    num_hidden_layers: 40
    max_position_embeddings: 8192
    attention_module: "multiquery_attention"
    attention_type: "scaled_dot_product"
    attention_softmax_fp32: True
    scale_qk_dot_by_layer_idx: False
    extra_attention_params:
        num_kv_groups: 1

    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True
    use_ffn_bias: True

    nonlinearity: "gelu"
    attention_dropout_rate: 0.1
    dropout_rate: 0.1

    layer_norm_epsilon: 1.0e-5
    use_bias_in_output: False
    initializer_range: 0.02

    loss_scaling: "num_tokens"

    output_layer_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.00223606797 # initializer_range / sqrt(2 * num_hidden_layers)
        a: -0.00447213595
        b: 0.00447213595

    mixed_precision: True
    fp16_type: "cbfloat16"

optimizer:
    # paper section 5.5
    optimizer_type: "adam"
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 0.1
    max_gradient_norm: 1.0
    learning_rate:
    - total_iters: 56888
      scheduler: "Linear"
      initial_learning_rate: 0.0
      end_learning_rate: 3.0e-4
    - scheduler: "CosineDecay"
      initial_learning_rate: 3.0e-4
      total_iters: 6724779
      end_learning_rate: 3.0e-5
    loss_scaling_factor: "dynamic"

runconfig:
    max_steps: 6781667       
    log_steps: 100
    checkpoint_steps: 5000
    seed: 1
