# Code LLaMa model, 7B parameters, max_seq_length 16384

train_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./shuffled/code_llama_dataset_vocab32016/val"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 18
    shuffle: False
    shuffle_seed: 1337
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./shuffled/code_llama_dataset_vocab32016/test"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 18
    shuffle: False
    num_workers: 8

model:
    # Embedding
    vocab_size: 32016
    hidden_size: 4096
    position_embedding_type: "rotary"
    rotary_dim: 128
    rope_theta: 1000000
    share_embedding_weights: False
    max_position_embeddings: 16384
    embedding_dropout_rate: 0.0

    # Decoder
    num_hidden_layers: 32
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5
    norm_type: "rmsnorm"

    # Decoder - Attention
    num_heads: 32
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: False
    use_ffn_bias_in_attention: False

    # Decoder - ffn
    filter_size: 11008
    nonlinearity: "swiglu"
    use_ffn_bias: False

    # Task-specific
    use_bias_in_output: False
    loss_scaling: "num_tokens"
    loss_weight: 1.0

    # Cerebras parameters
    mixed_precision: True
    fp16_type: "cbfloat16"

optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.95]
    eps: 1.0e-5
    correct_bias: True
    weight_decay: 0.1
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 3.0e-4
          total_iters: 113777
        - scheduler: "CosineDecay"
          initial_learning_rate: 3.0e-4
          end_learning_rate: 3.0e-5
          total_iters: 27012950
    loss_scaling_factor: "dynamic"

runconfig:
    max_steps: 27126727
    log_steps: 100
    checkpoint_steps: 10000
    save_initial_checkpoint: True
    seed: 1
    model_dir: "./model_dir"
    eval_steps: 233
