# LLaMa model, 32.5B parameters, max_seq_length 2048
# Based on: https://arxiv.org/pdf/2302.13971v1.pdf

train_input:
    data_processor: "GptHDF5MapDataProcessor" 
    data_dir: "./shuffled/llama_data_test/val"
    shuffle: False
    shuffle_seed: 1
    batch_size: 66
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

eval_input:
    data_processor: "GptHDF5MapDataProcessor" 
    data_dir: "./shuffled/llama_data_test/test"
    shuffle: False
    shuffle_seed: 1
    batch_size: 66
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

model:
    # Embedding
    vocab_size: 32000
    hidden_size: 6656
    position_embedding_type: "rotary"
    rotary_dim: 128
    share_embedding_weights: False
    max_position_embeddings: 2048
    embedding_dropout_rate: 0.0
    norm_type: "rmsnorm"

    # Decoder
    num_hidden_layers: 60
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-6

    # Decoder - Attention
    num_heads: 52
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: False
    use_ffn_bias_in_attention: False

    # Decoder - ffn
    filter_size: 17888
    nonlinearity: "swiglu"
    use_ffn_bias: False

    # Task-specific
    use_bias_in_output: False
    loss_scaling: "num_tokens"
    loss_weight: 1.0

    # Cerebras parameters
    fp16_type: "cbfloat16"
    mixed_precision: True

optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.95]
    correct_bias: True
    weight_decay: 0.1
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 2.69e-05 # sqrt(batch_size / 2048) * 1.5e-4
          total_iters: 59362
        - scheduler: "CosineDecay"
          initial_learning_rate: 2.69e-05 # sqrt(batch_size / 2048) * 1.5e-4
          end_learning_rate: 2.69e-06 # sqrt(batch_size / 2048) * 1.5e-5
          total_iters: 9847793
    max_gradient_norm: 1.0
    loss_scaling_factor: "dynamic"

runconfig:
    max_steps: 10357481      # Llama 33B was trained on 1.4T tokens.
                             # steps = 1.4T / (batch_size * 2048)
    log_steps: 100
    checkpoint_steps: 10000
    save_initial_checkpoint: True
    seed: 1
    model_dir: "./model_dir"
    eval_steps: 4404
