# LLaMa v2 model, 13B parameters, max_seq_length 4096
# Based on: https://arxiv.org/pdf/2307.09288.pdf

train_input:
    data_processor: "GptHDF5MapDataProcessor" 
    data_dir: "./shuffled/llama_v2_data_test/val"
    shuffle: False
    shuffle_seed: 1
    batch_size: 1024
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True


eval_input:
    data_processor: "GptHDF5MapDataProcessor" 
    data_dir: "./shuffled/llama_v2_data_test/test"
    shuffle: False
    shuffle_seed: 1
    batch_size: 1024
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

model:
    # Embedding
    vocab_size: 32000
    hidden_size: 5120
    position_embedding_type: "rotary"
    rotary_dim: 128
    share_embedding_weights: False
    max_position_embeddings: 4096
    embedding_dropout_rate: 0.0

    # Decoder
    num_hidden_layers: 40
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5
    norm_type: "rmsnorm"

    # Decoder - Attention
    num_heads: 40
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: False
    use_ffn_bias_in_attention: False

    # Decoder - ffn
    filter_size: 13824
    nonlinearity: "swiglu"
    use_ffn_bias: False

    # Task-specific
    use_bias_in_output: False
    loss_scaling: "num_tokens"
    loss_weight: 1.0

    # Cerebras parameters
    mixed_precision: True
    fp16_type: "cbfloat16"

optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.95]
    eps: 1.0e-5
    correct_bias: True
    weight_decay: 0.1
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 3.0e-4
          total_iters: 2000
        - scheduler: "CosineDecay"
          initial_learning_rate: 3.0e-4
          end_learning_rate: 3.0e-5
          total_iters: 474837
    max_gradient_norm: 1.0
    loss_scaling_factor: "dynamic"

runconfig:
    max_steps: 476837       # Llama v2 13B was trained on 2T tokens.
                            # steps = 2T / (1024 * 4096)
    log_steps: 100
    checkpoint_steps: 10000
    save_initial_checkpoint: True
    seed: 1
    model_dir: "./model_dir"
    eval_steps: 89
