trainer:
  init:
    backend:
      backend_type: CSX
    seed: 1
    model:
      name: "gptj"
      # Embedding
      vocab_size: 50277
      position_embedding_type: rotary
      share_embedding_weights: false
      embedding_dropout_rate: 0.0
      # Decoder Block
      hidden_size: 6144
      num_heads: 64
      num_hidden_layers: 44
      max_position_embeddings: 2048
      attention_type: scaled_dot_product
      attention_dropout_rate: 0.0
      residual_dropout_rate: 0.0
      use_untied_layer_norm: true
      use_projection_bias_in_attention: true
      use_ffn_bias_in_attention: true
      use_ffn_bias: true
      filter_size: 24576 # 4 * hidden_size
      nonlinearity: gelu
      rotary_dim: 24 # hidden_size / num_heads * 25%
      layer_norm_epsilon: 1.0e-05
      use_bias_in_output: false
      initializer_range: 0.02
      loss_scaling: num_tokens
      loss_weight: 1.0
      # We use truncated_normal instead of normal (ref: https://github.com/EleutherAI/gpt-neox),
      # with the same std and mean for better performance.
      embedding_initializer:
        name: truncated_normal
        mean: 0.0
        std: 0.00806871489 # sqrt(2 / (5 * hidden_size))
        a: -0.01613743
        b: 0.01613743
      initializer:
        name: truncated_normal
        mean: 0.0
        std: 0.00806871489 # sqrt(2 / (5 * hidden_size))
        a: -0.01613743
        b: 0.01613743
      output_layer_initializer:
        name: truncated_normal
        mean: 0.0
        std: 0.00057989813 # 2 / num_hidden_layers / sqrt(hidden_size)
        a: -0.001159796
        b: 0.001159796
      fp16_type: cbfloat16
      mixed_precision: true
    optimizer:
      adamw:
        betas:
        - 0.9
        - 0.95
        eps: 1.0e-08
        weight_decay: 0.01
        correct_bias: true
    # we want to keep the same number of tokens consistent with Eleuther gpt-neox 20B
    # Eleuther gpt-neox: steps * batch_size (1538) * seq_len (2048)
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            total_iters: 32041 # warm-up 0.01, 1500 * 1538 / 77
            initial_learning_rate: 0.0
            end_learning_rate: 2.09e-05 # sqrt(72 / 1538) * 0.97e-4
        - CosineDecayLR:
            initial_learning_rate: 2.09e-05
            total_iters: 3172125 # 148500 * 1538 / 72
            end_learning_rate: 2.09e-06 # end_learning_rate = initial_learning_rate * alpha. alpha = 1.0 - beta1, # sqrt(77 / 1538) * 0.97e-5
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
      max_gradient_norm: 1.0
    loop:
      max_steps: 3204166 # 150000 * 1538 / 72
      eval_frequency: 10000
    checkpoint:
      steps: 10000
    logging:
      log_steps: 100
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      data_dir:
      - ./shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/0/
      - ./shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/1/
      - ./shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/2/
      - ./shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/3/
      - ./shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/4/
      - ./shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/5/
      - ./shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/6/
      - ./shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/7/
      - ./shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/8/
      - ./shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/9/
      # The effective batch size, which is evenly divided across "num_csx" systems used for the run
      batch_size: 72
      shuffle: false
      shuffle_seed: 1337
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true # Important to avoid seeding at each epoch
    val_dataloader: &val_dataloader
      data_processor: GptHDF5MapDataProcessor
      data_dir: ./shuffled/language/datasets/pile_original/hdf5_dataset/val_neox_msl2048/
      batch_size: 72
      shuffle: false
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
  validate:
    val_dataloader: *val_dataloader
  validate_all:
    val_dataloaders: *val_dataloader
