# A 2.7B parameter muP Cerebras-GPT model configuration intended to run on a cluster
# of 4 CS-2s

train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir:
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/0/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/1/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/2/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/3/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/4/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/5/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/6/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/7/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/8/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/9/"
    shuffle: True
    shuffle_seed: 0
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 528 # 528 global = (66 micro)*(num_csx)*(grad accum steps)
    num_workers: 1
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./language/datasets/pile_original/hdf5_dataset/val_msl2048/"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 66
    shuffle: False
    num_workers: 1

### Model
model:
    # Embedding
    hidden_size: 2560
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 2048
    vocab_size: 50257

    # Decoder
    num_hidden_layers: 32
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5 # change to 1.0e-12 for single precision training


    # Decoder - Attention
    num_heads: 32
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Decoder - ffn
    filter_size: 10240
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Initializers
    embedding_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.08
        a: -0.16
        b: 0.16
    initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.025298221281347035
        a: -0.05059644256269407
        b: 0.05059644256269407
    output_layer_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.0031622776601683794
        a: -0.006324555320336759
        b: 0.006324555320336759

    # Task-specific
    loss_scaling: "batch_size" # needed for gradient accumulation
    loss_weight: 0.00048828125 # = 1/max_sequence_length
    use_bias_in_output: False

    # muP
    scale_qk_dot_by_d: True
    output_logits_scale: 0.1
    embeddings_scale: 10

    # Cerebras parameters
    mixed_precision: True
    fp16_type: "bfloat16"

### Optimization
optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.95]
    eps: 1.0e-8
    max_gradient_norm: 1.0
    learning_rate:
      - scheduler: "Linear"
        initial_learning_rate: 0.0
        end_learning_rate: 0.006
        total_iters: 346
      - scheduler: "CosineDecay"
        initial_learning_rate: 0.006
        end_learning_rate: 0.0006
        total_iters: 48695
    weight_decay: 0.1
    log_summaries: True
    correct_bias: True
    adjust_learning_rate:
        decoder_kernel: 0.1

### Cerebras parameters
runconfig:
    max_steps: 49041
    eval_steps: 2811
    checkpoint_steps: 2000
    enable_distributed: False
    log_steps: 1
    save_initial_checkpoint: False
    precision_opt_level: 0
