##############################################################
## Autoregressive LM Preprocessing Parameters with FIM Augmentation
##############################################################

setup:
    input_dir: "/cb/home/davidb/ws/monolith/tests/models/transformers/data_processing/hdf5_preprocessing/text_data"
    output_dir: "/cb/home/davidb/ws/monolith/tests/models/transformers/data_processing/hdf5_preprocessing/fim_data"
    processes: 1
    dataset_processor: "FIMDataPreprocessor"

processing:
    tokenizer_type: "NeoXTokenizer"
    encoder_file: "/cb/cold/checkpoints/llms/HF/starcoder/tokenizer.json"
    fim_prefix_tok: "<fim_prefix>"
    fim_middle_tok: "<fim_middle>"
    fim_suffix_tok: "<fim_suffix>"
    eos_id: 0
    
    max_seq_length: 2048 
    short_seq_prob: 0.0
    fim_rate: 0.9
    spm_rate: 0.5

    output_name: "examples"
    files_per_record: 50000
    write_in_batch: True

    write_remainder: True
    resume_from_checkpoint: False
    display_pbar: True
    seed: 0

dataset:
    use_ftfy: False
    ftfy_normalizer: "NFC"
    wikitext_detokenize: False

    jsonl_key: "text"
    pack_sequences: True
