setup:
    input_dir: "/cb/datasets/language/pile/raw_data/test/"
    output_dir: "./falcon_dataset"
    processes: 1
    dataset_processor: "LMDataPreprocessor"

processing:
    tokenizer_type: "HuggingFaceTokenizer"
    huggingface_tokenizer: "tiiuae/falcon-7b"
    max_seq_length: 2048
    short_seq_prob: 0.0

    output_name: "examples"
    files_per_record: 10000
    write_in_batch: True

    write_remainder: True
    resume_from_checkpoint: False
    display_pbar: True
    seed: 0

dataset:
    use_ftfy: True
    ftfy_normalizer: "NFC"
    wikitext_detokenize: False

    jsonl_key: "text"
    pack_sequences: True
