# Mistral model, 7B parameters, max_seq_length 32768
# Based on: https://mistral.ai/news/announcing-mistral-7b/

train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./mistral_data_test/val"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 12
    micro_batch_size: 4
    shuffle: True
    shuffle_seed: 1337
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch


eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./mistral_data_test/test"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 12
    micro_batch_size: 4
    shuffle: False
    num_workers: 8

model:
    # Embedding
    vocab_size: 32000
    hidden_size: 4096
    position_embedding_type: "rotary"
    rotary_dim: 128
    share_embedding_weights: False
    max_position_embeddings: 32768
    embedding_dropout_rate: 0.0

    # Decoder
    num_hidden_layers: 32
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5
    norm_type: "rmsnorm"

    # Decoder - Attention
    num_heads: 32
    attention_type: "scaled_dot_product"
    attention_module: "multiquery_attention"
    extra_attention_params:
        num_kv_groups: 8
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: False
    use_ffn_bias_in_attention: False
    attention_sliding_window_length: 4096

    # Decoder - ffn
    filter_size: 14336
    nonlinearity: "swiglu"
    use_ffn_bias: False

    # Task-specific
    use_bias_in_output: False

    # Cerebras parameters
    fp16_type: "cbfloat16"
    mixed_precision: True

optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.95]
    correct_bias: True
    weight_decay: 0.1
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 3.0e-4
          total_iters: 341333
        - scheduler: "CosineDecay"
          initial_learning_rate: 3.0e-4
          end_learning_rate: 3.0e-5
          total_iters: 40348672
    max_gradient_norm: 1.0
    loss_scaling_factor: "dynamic"

runconfig:
    # Note that Mistral training details are not released currently 
    # We might want to adjust these later 
    max_steps: 40690005      
    log_steps: 100
    checkpoint_steps: 10000
    save_initial_checkpoint: True
    seed: 1
    model_dir: "./model_dir"
    eval_steps: 233
