# DPO + Mistral model, 7B parameters, max_seq_length 1K
# Based on: https://huggingface.co/alignment-handbook/zephyr-7b-dpo-full

train_input:
    data_processor: "DpoHDF5DataProcessor"
    data_dir: "./ultrafeedback_binarized/train"
    batch_size: 128
    micro_batch_size: 32
    shuffle: True
    shuffle_seed: 1337
    num_workers: 8 
    prefetch_factor: 10
    persistent_workers: True

eval_input:
    data_processor: "DpoHDF5DataProcessor"
    data_dir: "./ultrafeedback_binarized/test"
    batch_size: 100
    micro_batch_size: 100
    shuffle: False
    num_workers: 8

model:
    dpo:
        beta: 0.01
        reference_free: False

    compute_eval_metrics: True

    model_name: "mistral"

    # Embedding
    vocab_size: 32000
    hidden_size: 4096
    position_embedding_type: "rotary"
    rotary_dim: 128
    share_embedding_weights: False
    max_position_embeddings: 32768
    embedding_dropout_rate: 0.0

    # Decoder
    num_hidden_layers: 32
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5
    norm_type: "rmsnorm"

    # Decoder - Attention
    num_heads: 32
    attention_type: "scaled_dot_product"
    attention_module: "multiquery_attention"
    extra_attention_params:
        num_kv_groups: 8
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: False
    use_ffn_bias_in_attention: False
    attention_sliding_window_length: 4096

    # Decoder - ffn
    filter_size: 14336
    nonlinearity: "swiglu"
    use_ffn_bias: False

    # Task-specific
    use_bias_in_output: False

    # Cerebras parameters
    fp16_type: "cbfloat16"
    mixed_precision: True

optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.999]
    eps: 1.0e-8
    correct_bias: True
    weight_decay: 0.0
    max_gradient_norm: 1.0
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 1.0e-8
          end_learning_rate: 5.0e-7 
          total_iters: 48  # 10% warmup steps
        - scheduler: "CosineDecay"
          initial_learning_rate: 5.0e-7
          end_learning_rate: 4.0e-10
          total_iters: 437 
    log_summaries: True
    loss_scaling_factor: "dynamic"

runconfig:
    max_steps: 485 # 3*149
    log_steps: 10
    checkpoint_steps: 100 
    save_initial_checkpoint: False
    precision_opt_level: 1
    load_checkpoint_states: model  
    seed: 1
    eval_steps: 20
