# Params for UNet model on Cityscapes dataset.

train_input: &train_input
    data_processor: CityscapesDataProcessor
    data_dir: "./cityscapes/"
    image_shape: [256, 512, 3]
    normalize_data_method: "zero_centered"
    augment_data: True
    shuffle: True
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 32
    num_classes: 20
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True
    use_worker_cache: True

eval_input:
    <<: *train_input
    augment_data: False
    shuffle: False
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 32
    num_workers: 2

model:
    nonlinearity: "ReLU"
    skip_connect: True
    enable_bias: True
    downscale_method: "max_pool"
    convs_per_block: ["3x3_conv", "3x3_conv"]
    encoder_filters: [32, 64, 128, 256, 512]
    decoder_filters: [256, 128, 64, 32]
    residual_blocks: False
    norm_layer: "group"
    norm_kwargs:
        num_groups: 16
    initializer: 
        "name": "glorot_uniform"
        "gain": 1.0
    bias_initializer: "zeros"
    # Loss for two classes only ("bce"),
    # Two or more classes ("multilabel_bce", "ssce")
    # bce -> Binary Cross Entropy With Logits
    # ssce -> Sparse Softmax Cross-Entropy
    loss: "ssce"
    mixed_precision: True
    use_bfloat16: True
    eval_ignore_classes: [0] # void classes to ignore in evaluation

optimizer:
    optimizer_type: "Adam"
    weight_decay: 0.0
    learning_rate:
        initial_learning_rate: 5.0e-4
        scheduler: "PiecewiseConstant"
        milestones: [10000]
        learning_rates: [5.0e-4, 1.0e-5]
    # Choices: `loss_scaling_factor`: {"dynamic", use values >= 1.0 for static loss scaling}
    # Note: When `use_bfloat16: True`, this always defaults to `1.0`
    loss_scaling_factor: 1.0

runconfig:
    max_steps: 15000
    log_steps: 100
    checkpoint_steps: 15000
    seed: 1
    save_initial_checkpoint: True
    num_csx: 1
    num_act_servers: 1
    num_wgt_servers: 1
    num_workers_per_csx: 1
    compile_crd_memory_gi: 90
    wrk_memory_gi: -1
