# Params for UNet model on Inria Aerial Dataset 5120 x 5120 images

train_input: &train_input
    data_processor: InriaAerialDataProcessor
    data_dir: "./computer_vision/datasets/AerialImageDataset_5120_5120" # ON CS
    image_shape: [5120, 5120, 3]  # [H, W, C]
    normalize_data_method: "zero_centered"
    augment_data: True
    shuffle: True
    shuffle_seed: 1234
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 1
    num_classes: 2
    num_workers: 4
    prefetch_factor: 10
    persistent_workers: True
    use_worker_cache: True

    use_fast_dataloader: False # Toggle to True for faster MAP style dataloader

eval_input: &eval_input
    <<: *train_input
    augment_data: False
    image_shape: [5120, 5120, 3]
    shuffle: False
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 1
    num_workers: 2


model:
    nonlinearity: "ReLU"
    skip_connect: True
    enable_bias: True
    downscale_method: "max_pool"
    convs_per_block: ["3x3_conv", "3x3_conv"]
    encoder_filters: [32, 64, 128, 256, 512, 1024]
    decoder_filters: [512, 256, 128, 64, 32]
    residual_blocks: False
    initializer: 
        "name": "glorot_uniform"
        "gain": 1.0
    bias_initializer: "zeros"
    # bce -> Binary Cross Entropy With Logits
    loss: "bce"
    mixed_precision: True
    norm_layer: "group"
    norm_kwargs:
        num_groups: 16
    use_bfloat16: True

optimizer:
    optimizer_type: AdamW
    correct_bias: True
    weight_decay: 0.01
    max_gradient_norm: 1.0
    learning_rate:
       - scheduler: "Linear"
         initial_learning_rate: 0.0
         end_learning_rate: 0.00025
         total_iters: 4000
       - scheduler: "Linear"
         initial_learning_rate: 0.00025
         end_learning_rate: 0.0
         total_iters: 10000
    # Choices: `loss_scaling_factor`: {"dynamic", use values >= 1.0 for static loss scaling}
    # Note: When `use_bfloat16: True`, this always defaults to `1.0`
    loss_scaling_factor: 1.0

runconfig:
    max_steps: 10000
    log_steps: 1
    checkpoint_steps: 10000
    seed: 1
    save_initial_checkpoint: True
    num_csx: 1
    num_act_servers: 4
    num_wgt_servers: 1
    num_workers_per_csx: 16
    compile_crd_memory_gi: 90
    wrk_memory_gi: -1
