# MPT model, 7B parameters, max_seq_length 2048
# Based on: https://huggingface.co/mosaicml/mpt-7b

train_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./shuffled/mpt_data_test/val"
    shuffle: False
    shuffle_seed: 1
    batch_size: 99
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

eval_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./shuffled/mpt_data_test/test"
    shuffle: False
    shuffle_seed: 1
    batch_size: 99
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

model:
    # Embedding
    vocab_size: 50432
    hidden_size: 4096
    position_embedding_type: alibi
    share_embedding_weights: True
    max_position_embeddings: 2048
    embedding_dropout_rate: 0
    embedding_layer_norm: false

    # Decoder
    num_hidden_layers: 32
    dropout_rate: 0
    layer_norm_epsilon: 1.0e-5
    norm_type: biasless-layernorm

    # Decoder - Attention
    num_heads: 32
    attention_module: "aiayn_attention"
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0
    use_projection_bias_in_attention: False
    use_ffn_bias_in_attention: False

    # Decoder - ffn
    filter_size: 16384
    nonlinearity: "gelu"
    use_ffn_bias: False

    # Task-specific
    use_bias_in_output: False
    loss_weight: 0.00048828125 # = 1/max_sequence_length

    # Cerebras parameters
    mixed_precision: True
    fp16_type: "cbfloat16"

# MPT docs don't reveal optimization settings. These are from GPT2:
optimizer:
    optimizer_type: "AdamW"
    correct_bias: True
    weight_decay: 0.01
    loss_scaling_factor: "dynamic"
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 3.1e-05
          total_iters: 20686
        - scheduler: "Linear"
          initial_learning_rate: 3.1e-05
          end_learning_rate: 0.0
          total_iters: 39436381

runconfig:
    max_steps: 39457067      # MPT was trained on 1T tokens.
                              # steps = 1T / (batch_size * 2048)
    log_steps: 100
    checkpoint_steps: 10000
    save_initial_checkpoint: True
    seed: 1
    model_dir: "./model_dir"
    eval_steps: 1622
    execute_crd_memory_gi: -1
