#BERT-NER-Base

train_input:
    data_processor: "BertTokenClassifierDataProcessor"
    data_dir: "./language/datasets/ner-pt/bc5cdr-chem-csv/train"
    vocab_file: "../../../../vocab/Pubmed_fulltext_vocab.txt"
    label_vocab_file: "./language/datasets/ner-pt/bc5cdr-chem-csv/train/label2id.json"
    max_sequence_length: 128
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 4096
    shuffle: True
    num_workers: 1

eval_input:
    data_processor: "BertTokenClassifierDataProcessor"
    data_dir: "./language/datasets/ner-pt/bc5cdr-chem-csv/dev"
    vocab_file: "../../../../vocab/Pubmed_fulltext_vocab.txt"
    label_vocab_file: "./language/datasets/ner-pt/bc5cdr-chem-csv/train/label2id.json"
    max_sequence_length: 128
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 12
    shuffle: False
    num_workers: 1

model:
    vocab_size: 30522
    hidden_size: 768
    num_hidden_layers: 12
    num_heads: 12
    filter_size: 3072
    encoder_nonlinearity: "gelu"
    pooler_nonlinearity: "tanh"
    max_position_embeddings: 512
    encoder_output_dropout_rate: 0.1
    num_classes: 7
    mixed_precision: True
    compute_eval_metrics: False
    include_padding_in_loss: True

optimizer:
    optimizer_type: "Adam" # {"SGD", "AdamW", "Adam"}
    eps: 1.e-6
    max_gradient_norm: 1.0
    learning_rate:
        - scheduler: "Linear"
          total_iters: 1508  # 10% of max_steps
          initial_learning_rate: 0.0
          end_learning_rate: 0.00001
        - scheduler: "Linear"
          total_iters: 15080
          initial_learning_rate: 0.00001
          end_learning_rate: 0
    loss_scaling_factor: "dynamic"

runconfig:
    max_steps: 15080 # 20 epochs
    log_steps: 100
    checkpoint_steps: 1000
    seed: 1
    model_dir: "./model_dir"
    eval_steps: 759
    use_cs_grad_accum: True
