###################################################################
## Base configuration (2nd stage): BTLM 2.7B model with 8k-MSL
###################################################################

train_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./language/datasets/SlimPajama/train_shuffled_msl8192/"
    shuffle: False 
    shuffle_seed: 1
    batch_size: 480
    use_worker_cache: False
    num_workers: 8

eval_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./language/datasets/SlimPajama/val_msl8192/"
    batch_size: 15
    shuffle: False
    use_worker_cache: False
    num_workers: 8

### Model
model:
    # Embedding
    hidden_size: 2560
    position_embedding_type: "alibi"
    share_embedding_weights: True
    max_position_embeddings: 8192
    vocab_size: 50257

    # Decoder
    num_hidden_layers: 32
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5 # change to 1.0e-12 for single precision training

    # Decoder - Attention
    num_heads: 32
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Decoder - ffn
    filter_size: 6826
    nonlinearity: "swiglu"
    use_ffn_bias: True

    # Initializers
    embedding_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.073
        a: -0.146
        b: 0.146
    initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.023084626919229165
        a: -0.04616925383845833
        b: 0.04616925383845833
    output_layer_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.0028855783649036457
        a: -0.005771156729807291
        b: 0.005771156729807291

    # Task-specific
    loss_scaling: batch_size
    loss_weight: 0.0001220703125 # = 1/max_sequence_length
    use_bias_in_output: False

    # Cerebras parameters
    mixed_precision: True
    fp16_type: "cbfloat16"

    output_logits_scale: 0.22200000000000003
    scale_qk_dot_by_d: True
    embeddings_scale: 14.6

### Optimization
optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.95]
    eps: 1.0e-8
    max_gradient_norm: 1.0
    learning_rate:
      - scheduler: "Linear"
        initial_learning_rate: 0.0
        end_learning_rate: 0.012
        total_iters: 95
      - scheduler: "Linear"
        initial_learning_rate: 0.012
        end_learning_rate: 1.0198e-04
        total_iters: 159541
    adjust_learning_rate:
        decoder_kernel: 0.1
    weight_decay: 0.1
    log_summaries: True
    correct_bias: True

    loss_scaling_factor: "dynamic"
### Cerebras parameters
runconfig:
    max_steps: 159636
    eval_steps: 8688
    enable_distributed: False
    checkpoint_steps: 200
    log_steps: 1
    save_initial_checkpoint: False
    seed: 1
    precision_opt_level: 1
