##############################################################
## Base configuration: GPT-3 XL model (1.3B parameters)
##############################################################

train_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir:
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/0/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/1/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/2/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/3/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/4/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/5/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/6/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/7/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/8/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/9/"
    shuffle: False # data is expected to be shuffled during preprocessing
    shuffle_seed: 0
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 528 # 528 global = (88 micro)*(num_csx)*(grad accum steps)
    micro_batch_size: 88 # forcing this micro batch size will lead to best performance but could be changed for better convergence
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./language/datasets/pile_original/hdf5_dataset/val_msl2048/"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 264
    shuffle: False
    num_workers: 8

### Model
model:
    # Embedding
    vocab_size: 50257
    hidden_size: 2048
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 2048

    # Decoder
    num_hidden_layers: 24
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5 # change to 1.0e-12 for single precision training

    # Decoder - Attention
    num_heads: 16
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Decoder - ffn
    filter_size: 8192
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Task-specific
    # loss_scaling defaults to num_tokens
    use_bias_in_output: False
    loss_scaling: "num_tokens"
    loss_weight: 1.0

    # Initializers
    embedding_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.02
        a: -0.04
        b: 0.04

    initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.02
        a: -0.04
        b: 0.04

    output_layer_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.0025
        a: -0.005
        b: 0.005

    # Cerebras parameters
    mixed_precision: True
    fp16_type: "cbfloat16"

### Optimization
optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 0.1
    max_gradient_norm: 1.0
    correct_bias: True
    learning_rate:
      - scheduler: "Linear"
        initial_learning_rate: 0.0
        end_learning_rate: 0.0002
        total_iters: 346
      - scheduler: "CosineDecay"
        initial_learning_rate: 0.0002
        end_learning_rate: 2.0e-05
        total_iters: 23988
    log_summaries: True

    loss_scaling_factor: "dynamic"
### Cerebras parameters
runconfig:
    max_steps: 24334
    eval_steps: 702
    checkpoint_steps: 2000
    enable_distributed: False
    log_steps: 1
    save_initial_checkpoint: False
