# GPT-NeoX 6.7B params
# reference: https://github.com/EleutherAI/gpt-neox/blob/main/configs/6-7B.yml
train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir:
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/0/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/1/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/2/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/3/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/4/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/5/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/6/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/7/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/8/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/9/"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 120
    shuffle: True
    shuffle_seed: 1337
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./language/datasets/pile_original/hdf5_dataset/val_neox_msl2048/"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 120
    shuffle: False
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

model:
    # Embedding
    vocab_size: 50277
    position_embedding_type: "rotary"
    share_embedding_weights: False
    embedding_dropout_rate: 0.0

    # Decoder Block
    hidden_size: 4096
    num_heads: 32
    num_hidden_layers: 32
    max_position_embeddings: 2048
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    residual_dropout_rate: 0.0

    use_untied_layer_norm: True
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True
    use_ffn_bias: True

    filter_size: 16384 # 4 * hidden_size
    nonlinearity: "gelu"

    rotary_dim: 128 # 1 * 4096 / 32
    layer_norm_epsilon: 1.0e-5
    use_bias_in_output: False
    initializer_range: 0.02

    loss_scaling: "batch_size"
    loss_weight: 0.00048828125 # = 1/max_sequence_length

    # We use truncated_normal instead of normal (ref: https://github.com/EleutherAI/gpt-neox),
    # with the same std and mean for better performance.
    embedding_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.00988211768802619 # sqrt(2 / (5 * hidden_size))
        a: -0.0197642353760524
        b: 0.0197642353760524

    initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.00988211768802619 # sqrt(2 / (5 * hidden_size))
        a: -0.0197642353760524
        b: 0.0197642353760524

    output_layer_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.0009765625 # 2 / num_hidden_layers / sqrt(hidden_size)
        a: -0.001953125
        b: 0.001953125

    mixed_precision: True

optimizer:
    optimizer_type: "adamw"
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 0.1
    max_gradient_norm: 1.0
    correct_bias: True
    # we want to keep the same number of tokens consistent with Eleuther gpt-neox 20B
    # Eleuther gpt-neox: steps * batch_size (1538) * seq_len (2048)
    learning_rate:
        - total_iters: 41013 # 1% warmup steps
          scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 3.983e-5 # assumes square root scaling with batch size 120 
        - scheduler: "CosineDecay"
          initial_learning_rate: 3.983e-5
          total_iters: 4060320 # 320000 * 1538 / 120 - 41013
          end_learning_rate: 3.983e-6

runconfig:
    max_steps: 4101333 # 320000 * 1538 / 120
    log_steps: 100
    checkpoint_steps: 10000
    use_cs_grad_accum: True
    seed: 1
