# GPT-Neox small model
# Based on https://github.com/EleutherAI/gpt-neox/blob/main/configs/small.yml
train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: 
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/0/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/1/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/2/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/3/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/4/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/5/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/6/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/7/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/8/"
        - "./language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/9/"
    # batch_size = train_micro_bs * num_gpus * grad_accum_step / (model_parallel_size * pipeline_parallel_size)
    # based on the conversation with authors, this is our best guess on the batch sizes they used
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 256
    shuffle: True
    shuffle_seed: 1337
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./language/datasets/pile_original/hdf5_dataset/val_neox_msl2048/"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 256
    shuffle: False
    num_workers: 8

model:
    # Embedding
    vocab_size: 50277 
    position_embedding_type: "rotary"
    share_embedding_weights: False
    embedding_dropout_rate: 0.0

    # Decoder Block
    hidden_size: 768
    num_heads: 12
    num_hidden_layers: 12
    max_position_embeddings: 2048
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    residual_dropout_rate: 0.0

    use_untied_layer_norm: True
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True
    use_ffn_bias: True

    filter_size: 3072 # 4 * hidden_size
    nonlinearity: "gelu"

    rotary_dim: 16 # hidden_size / num_heads * 25%
    layer_norm_epsilon: 1.0e-5
    use_bias_in_output: False
    initializer_range: 0.02

    loss_scaling: "batch_size"
    loss_weight: 0.00048828125 # = 1/max_sequence_length

    # We use truncated_normal instead of normal ("ref: https://github.com/EleutherAI/gpt-neox/blob/main/configs/small.yml") with the same std and mean for better performance
    # Neox small config uses normal init with std=0.02, we chose to align with Neox 20B
    embedding_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.02282177322 # sqrt(2 / (5 * hidden_size))

    initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.02282177322 # sqrt(2 / (5 * hidden_size))

    output_layer_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.0060140653 # 2 / num_hidden_layers / sqrt(hidden_size)

    mixed_precision: True

optimizer:
    optimizer_type: "adamw"
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.0
    max_gradient_norm: 1.0
    correct_bias: True
    learning_rate:
        - total_iters: 3200 # warm-up 0.01
          scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 0.0006
        - scheduler: "CosineDecay"
          initial_learning_rate: 0.0006
          total_iters: 316800
          end_learning_rate: 0.00006 # end_learning_rate = initial_learning_rate * alpha. alpha = 1.0 - beta1

runconfig:
    max_steps: 320000
    log_steps: 100
    checkpoint_steps: 10000
    use_cs_grad_accum: True
    seed: 1

