# Copyright 2023 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##############################################################
## Base configuration: BLOOM 7.1B model
##############################################################
train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./bloom_data_test/val/"
    shuffle: True
    shuffle_seed: 1337
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 99
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./bloom_data_test/test/"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 99
    shuffle: False
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

model:
    # Embedding
    vocab_size: 250880
    hidden_size: 4096
    use_position_embedding: True
    position_embedding_type: "alibi"
    alibi_trainable_slopes: False
    share_embedding_weights: True
    max_position_embeddings: 2048
    embedding_layer_norm: True

    # Decoder
    num_hidden_layers: 30
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5

    # Decoder - Attention
    attention_kernel: "default"
    num_heads: 32
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    # the following attention & ffn biases are set based on https://github.com/huggingface/transformers/blob/d896029e273d118b29bea4ef24daa4d2c074c419/src/transformers/models/bloom/modeling_bloom.py#L235-L236
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Decoder - ffn
    filter_size: 16384 # 4 * hidden_size
    nonlinearity: "gelu"
    use_ffn_bias: True # As set in https://github.com/huggingface/transformers/blob/d896029e273d118b29bea4ef24daa4d2c074c419/src/transformers/models/bloom/modeling_bloom.py#L379

    # Task-specific
    use_bias_in_output: False # As set in https://github.com/huggingface/transformers/blob/d896029e273d118b29bea4ef24daa4d2c074c419/src/transformers/models/bloom/modeling_bloom.py#L831

    embedding_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.02

    initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.02

    output_layer_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.02

    # Cerebras parameters
    mixed_precision: True

optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 0.1
    max_gradient_norm: 1.0
    correct_bias: True
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 5.26e-5 # sqrt(batch_size / 512) * 1.2e-4
          total_iters: 1848 # approx 375M tokens at batch size 99 and msl 2048
        - scheduler: "CosineDecay"
          initial_learning_rate: 5.26e-5
          end_learning_rate: 5.26e-6 # sqrt(batch_size / 512) * (1.0e-5)
          total_iters: 2022181 # approx 410B tokens at batch size 99 and msl 2048
        - scheduler: "Constant"
          learning_rate: 2.84e-6

runconfig:
    max_steps: 2024029 # BLOOM models are trained for approx 410B tokens
    log_steps: 100
    checkpoint_steps: 10000
    seed: 1
    eval_steps: 1873 # 185646 / batch_size - 1
    execute_crd_memory_gi: 45
    use_cs_grad_accum: True
