# A 125M parameter Cerebras-GPT model configuration designed for a single CS-2
# to run 50% SparseWide-IFT runs with static sparsity, runs with gradient accumulation enabled

### Training Data
train_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./language/datasets/wikitext-103_hdf5/train/"
    shuffle: False
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 512 # 512 global = (512 micro)*(1 csx)*(1 grad accum step)
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

### Validation Data
eval_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./language/datasets/wikitext-103_hdf5/valid/"
    shuffle: False
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 231 ## only 231 samples in validation dataset
    num_workers: 1
    prefetch_factor: 10
    persistent_workers: True

### Model
model:
    # Embedding
    hidden_size: 1092
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 1024
    vocab_size: 50257

    # Decoder
    num_hidden_layers: 12
    dropout_rate: 0.1
    layer_norm_epsilon: 1.0e-5

    # Decoder - Attention
    num_heads: 12
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.1
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Decoder - ffn
    filter_size: 4368
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Initializers
    embedding_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.02
        a: -0.04
        b: 0.04

    initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.02
        a: -0.04
        b: 0.04

    output_layer_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.004082482904638631
        a: -0.008164965809277261
        b: 0.008164965809277261

    # Task-specific
    loss_scaling: "num_tokens"
    loss_weight: 1.0
    use_bias_in_output: False

    # Cerebras parameters
    mixed_precision: True
    fp16_type: "cbfloat16"

### Optimization
optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.95]
    eps: 1.0e-8
    max_gradient_norm: 1.0
    learning_rate:
      - scheduler: "Linear"
        initial_learning_rate: 0.0
        end_learning_rate: 6.0e-04
        total_iters: 2151 # 10 epochs with Seq. Length = 1024 and Batch Size = 512
      - scheduler: "CosineDecay"
        initial_learning_rate: 6.0e-04
        end_learning_rate: 6.0e-05
        total_iters: 19360
    weight_decay: 0.1
    correct_bias: True
    log_summaries: True

    loss_scaling_factor: "dynamic"
### Sparsity
sparsity:
    sparsity: 0.50
    init_method: "random"
    param_filter:
      - "*proj_[qkv]_dense_layer.weight"
      - "*proj_output_dense_layer.weight"
      - "*linear_layer.weight"

### Cerebras parameters
runconfig:
    max_steps: 21511 # 100 epochs with Seq. Length = 1024 and Batch Size = 512
    eval_steps: 1
    checkpoint_steps: 2152
    enable_distributed: False
    log_steps: 1
    save_initial_checkpoint: False
    precision_opt_level: 1
