# Santacoder model, 1B parameters, max_seq_length 2048
# Based on: https://arxiv.org/pdf/2301.03988.pdf

train_input:  
    data_processor : "GptHDF5MapDataProcessor"
    data_dir: "./shuffled/santacoder_data_test/val"
    shuffle: False
    shuffle_seed: 1
    batch_size: 192
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

eval_input:  
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./shuffled/santacoder_data_test/test"
    shuffle: False
    shuffle_seed: 1
    batch_size: 192
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

model: 
    # Embedding
    vocab_size: 49280
    position_embedding_type: "learned"
    embedding_dropout_rate: 0.1
    share_embedding_weights: True # no config default values, HF uses tie_weights as default

    # Decoder Block
    hidden_size: 2048
    filter_size: 8192
    num_heads: 16
    num_hidden_layers: 24
    max_position_embeddings: 2048
    attention_module: "multiquery_attention"
    attention_type: "scaled_dot_product"
    attention_softmax_fp32: True
    extra_attention_params:
        num_kv_groups: 1

    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True
    use_ffn_bias: True

    nonlinearity: "gelu"
    attention_dropout_rate: 0.1
    dropout_rate: 0.1

    layer_norm_epsilon: 1.0e-5
    use_bias_in_output: False
    initializer_range: 0.02

    mixed_precision: True
    fp16_type: "cbfloat16"

optimizer: 
    optimizer_type: "Adam"
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 0.1
    learning_rate:
    - scheduler: "Linear"
      total_iters: 12000
      initial_learning_rate: 0.0
      end_learning_rate: 2.0e-4
    - scheduler: "CosineDecay"
      initial_learning_rate: 2.0e-4
      total_iters: 588000
      end_learning_rate: 0.0  
    loss_scaling_factor: "dynamic"
runconfig:  
    max_steps: 600000  # in Section 6.2
    log_steps: 100
    checkpoint_steps: 5000
    seed: 1
    precision_opt_level: 0
